vault:
  address: https://hash.navarra-lab.com
  app_role_id: ad1f3e75-cf35-0200-c2c2-596e648c87bc
  listened_event_type: kv-v2/*

  # enter a duration string such as "2h45m".
  #Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
  scheduled_snapshot_interval: 12h

  log_file_path: vault_backup.log
  snapshot_folder: /home/navarra/vault/backups
  web_socket_event_base_url: wss://hash.navarra-lab.com:8400

google_drive:
  on_event_deploy_folder_id: 1-LAQ9Vy2OtCPq4VvqfZqTWRE085G8ie8
  scheduled_deploy_folder_id: 1WPGap6G_7scjpdJLB7BSb4uH7vJyyVer
  backup_file_retention_days: 30
